import os
import argparse
from filesmith.core.project import Project
from filesmith.utils.colors import parse_rgb_color
from filesmith.generators.checkerboard import generate_checkerboard
from filesmith.generators.stripes import generate_stripes
from filesmith.generators.gradient import generate_gradient
from filesmith.exporters.ppm_exporter import save_as_ppm_p3, save_as_ppm_p6
from filesmith.exporters.txt_exporter import save_as_txt
from filesmith.core.report import print_report, save_report
from filesmith.exporters.svg_exporter import save_as_svg
from filesmith.exporters.html_exporter import save_report_html
from filesmith.exporters.bmp_exporter import save_as_bmp
from filesmith.utils.image_scaling import scale_image_nearest

ALL_FORMATS = ['p3', 'p6', 'svg', 'bmp', 'txt', 'report', 'html']

def parse_args():
    parser = argparse.ArgumentParser(description="FileSmith image generator")
    parser.add_argument('--width', type=int, default=16)
    parser.add_argument('--height', type=int, default=16)
    parser.add_argument('--cell-size', type=int, default=4)
    parser.add_argument('--output-dir', type=str, default='exports')
    parser.add_argument('--formats', nargs='+', choices=ALL_FORMATS, default=ALL_FORMATS)
    parser.add_argument('--pattern', choices=['checkerboard', 'stripes', 'gradient'], default='checkerboard')
    parser.add_argument('--direction', choices=['horizontal', 'vertical'], default='horizontal')
    parser.add_argument('--color-a', type=parse_rgb_color, default=(255, 255, 255))
    parser.add_argument('--color-b', type=parse_rgb_color, default=(0, 0, 0))
    parser.add_argument('--svg-scale', type=int, default=20)
    parser.add_argument('--bmp-scale', type=int, default=1)
    return parser.parse_args()


def validate_args(args):
    if args.width <= 0:
        print("Error: --width must be greater than 0.")
        return False
    if args.height <= 0:
        print("Error: --height must be greater than 0.")
        return False
    if args.cell_size <= 0:
        print("Error: --cell-size must be greater than 0.")
        return False
    if args.svg_scale <= 0:
        print("Error: --svg-scale must be greater than 0.")
        return False
    if args.bmp_scale <= 0:
        print("Error: --bmp-scale must be greater than 0.")
        return False
    return True


def main():
    args = parse_args()

    if not validate_args(args):
        return

    os.makedirs(args.output_dir, exist_ok=True)

    base_name = args.pattern
    title = f"{args.pattern.capitalize()} Test"
    description = f"A simple {args.pattern} image generated by FileSmith."

    project = Project(title=title, description=description)

    color_a = args.color_a
    color_b = args.color_b

    if args.pattern == 'checkerboard':
        image_object = generate_checkerboard(args.width, args.height, args.cell_size, color_a, color_b)
    elif args.pattern == 'stripes':
        image_object = generate_stripes(args.width, args.height, args.cell_size, color_a, color_b, args.direction)
    elif args.pattern == 'gradient':
        image_object = generate_gradient(args.width, args.height, color_a, color_b, args.direction)

    project.set_image(image_object)

    fmt = args.formats

    # Image/data exports
    if 'p3' in fmt:
        path = os.path.join(args.output_dir, f"{base_name}_ascii.ppm")
        if save_as_ppm_p3(path, image_object):
            project.add_export_path(path)

    if 'p6' in fmt:
        path = os.path.join(args.output_dir, f"{base_name}_binary.ppm")
        if save_as_ppm_p6(path, image_object):
            project.add_export_path(path)

    if 'svg' in fmt:
        path = os.path.join(args.output_dir, f"{base_name}.svg")
        if save_as_svg(path, image_object, args.svg_scale):
            project.add_export_path(path)

    if 'bmp' in fmt:
        path = os.path.join(args.output_dir, f"{base_name}.bmp")
        bmp_image = scale_image_nearest(image_object, args.bmp_scale) if args.bmp_scale > 1 else image_object
        if save_as_bmp(path, bmp_image):
            project.add_export_path(path)

    if 'txt' in fmt:
        path = os.path.join(args.output_dir, f"{base_name}.txt")
        if save_as_txt(path, image_object):
            project.add_export_path(path)

    # Report exports — path added before saving so report lists itself
    if 'report' in fmt:
        path = os.path.join(args.output_dir, f"{base_name}_report.txt")
        project.add_export_path(path)
        save_report(project, path)

    if 'html' in fmt:
        path = os.path.join(args.output_dir, f"{base_name}_report.html")
        project.add_export_path(path)
        save_report_html(path, project)

    print_report(project)


if __name__ == "__main__":
    main()
