import os
from filesmith.core.project import Project
from filesmith.generators.checkerboard import generate_checkerboard
from filesmith.exporters.ppm_exporter import save_as_ppm_p3, save_as_ppm_p6
from filesmith.exporters.txt_exporter import save_as_txt
from filesmith.core.report import print_report, save_report
from filesmith.exporters.svg_exporter import save_as_svg
from filesmith.exporters.html_exporter import save_report_html

def main():
    os.makedirs("exports", exist_ok=True)

    project = Project(title="Checkerboard Test", description="A simple checkerboard image generated by FileSmith.")

    width, height, cell_size = 16, 16, 4
    white, black = (255, 255, 255), (0, 0, 0)

    image_object = generate_checkerboard(width, height, cell_size, white, black)
    project.set_image(image_object)

    ascii_path = "exports/checkerboard_ascii.ppm"
    binary_path = "exports/checkerboard_binary.ppm"

    save_as_ppm_p3(ascii_path, image_object)
    project.add_export_path(ascii_path)

    save_as_ppm_p6(binary_path, image_object)
    project.add_export_path(binary_path)

    txt_path = "exports/checkerboard.txt"
    save_as_txt(txt_path, image_object)
    project.add_export_path(txt_path)

    report_path = "exports/checkerboard_report.txt"
    save_report(project, report_path)
    project.add_export_path(report_path)

    report_path = "exports/checkerboard.svg"
    save_as_svg(report_path, image_object, 200)
    project.add_export_path(report_path)

    html_path = "exports/checkerboard_report.html"
    save_report_html(html_path, project)
    project.add_export_path(html_path)

    print_report(project)



if __name__ == "__main__":
    main()